---
- name: Add deflate settings
  template:
    src: deflate.conf
    dest: '{{ apache_conf_path }}/deflate.conf'

- name: Add mpm settings
  template:
    src: mpm.conf
    dest: '{{ apache_conf_path }}/mpm.conf'

- name: Disable mpm_prefork
  lineinfile:
    dest: '{{ apache_server_root }}/conf.modules.d/00-mpm.conf'
    regexp: '^LoadModule mpm_prefork_module modules/mod_mpm_prefork.so'
    line: '# LoadModule mpm_prefork_module modules/mod_mpm_prefork.so'

- name: Enable mpm_event
  lineinfile:
    dest: '{{ apache_server_root }}/conf.modules.d/00-mpm.conf'
    regexp: '^# ?LoadModule mpm_event_module modules/mod_mpm_event.so'
    line: 'LoadModule mpm_event_module modules/mod_mpm_event.so'
