---
- name: Create app folder
  file:
    path: '{{ projects_folder }}/{{ project_name }}'
    owner: '{{ apache_user }}'
    group: '{{ apache_user }}'
    mode: 0775
    state: directory
  register: folder_result

- name: Create index file
  template:
    src: index.php
    dest: '{{ projects_folder }}/{{ project_name }}/index.php'
    owner: '{{ user }}'
    group: '{{ user }}'
  when: folder_result|changed

- name: Add deflate settings
  template:
    src: deflate.conf
    dest: '{{ apache_conf_path }}/deflate.conf'

- name: Add mpm settings
  template:
    src: mpm.conf
    dest: '{{ apache_conf_path }}/mpm.conf'
