---
- name: Configure user
  user:
    name: '{{ user }}'
    append: yes
    groups: '{{ apache_user }}'

- name: Create app folder
  file:
    path: '{{ project_remote_folder }}'
    owner: '{{ apache_user }}'
    group: '{{ apache_user }}'
    mode: 0775
    state: directory

- include: apache.yml
- include: php.yml
