---
- name: Configure user
  user:
    name: '{{ user }}'
    createhome: no
    append: yes
    groups: apache

- name: Create app folder
  file:
    path: '{{ project_remote_folder }}'
    owner: apache
    group: apache
    mode: 0775
    state: directory

- include: apache.yml
- include: php.yml
