---
- name: Modify settings on php-fpm
  lineinfile:
    dest: '{{ php_fpm_pool_conf_path }}'
    regexp: ';?{{ item.setting }} ?=.*'
    line: '{{ item.setting }} = {{ item.value }}'
  with_items: '{{ php_fpm_settings }}'

- name: Modify settings on php.ini
  lineinfile:
    dest: '{{ item.0 }}/php.ini'
    regexp: ';?{{ item.1.setting }} ?=.*'
    line: '{{ item.1.setting }} = {{ item.1.value }}'
  with_together:
    - '{{ php_conf_paths }}'
    - '{{ php_settings }}'

- name: Enable apc.so
  lineinfile:
    dest: '{{ item }}/{{ php_apc_conf_filename }}'
    line: 'extension=apc.so'
  with_items: '{{ php_extension_conf_paths }}'
