---
- hosts: "{{ target|default('none') }}"
  become: true
  vars_files:
    - vars.yml
  gather_facts: false
  pre_tasks:
    - name: Ensure python is installed
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: false
    - name: Include dynamic vars depending on configuration
      include_vars:
        file: '{{ configuration }}.yml'
      ignore_errors: yes
    - setup: # gather_facts
  roles:
    - before
    - yatesr.timezone
    - Stouts.locale
    - GROG.package
    - geerlingguy.certbot
    - geerlingguy.nginx
    - geerlingguy.mysql
    - geerlingguy.php
    - geerlingguy.composer
    - cron
    - after
