---
user: provision
project_name: project
project_remote_folder: '/var/www/{{ project_name }}'
project_relative_index_path: web

# Locale
locale_locales:
  - es_ES.UTF-8

# Timezone
timezone: Europe/Madrid

# Packages
package_list:
  - name: gcc
  - name: git
  - name: zip
  - name: unzip
  - name: https://centos7.iuscommunity.org/ius-release.rpm

# PHP
php_date_timezone: '{{ timezone }}'
php_error_reporting: 'E_ALL & ~E_DEPRECATED'
php_display_startup_errors: 'Off'
php_opcache_revalidate_path: '1'
php_opcache_enable_cli: '1'
php_opcache_max_accelerated_files: '20000'
php_realpath_cache_size: '5M'

php_enablerepo: ius
php_packages:
  - php70u-devel
  - php70u-cli
  - php70u-fpm-httpd
  - php70u-gd
  - php70u-intl
  - php70u-json
  - php70u-mbstring
  - php70u-mcrypt
  - php70u-mysqlnd
  - php70u-opcache
  - php70u-xml
  - php70u-pecl-apcu
  - php70u-pecl-apcu-devel
php_enable_php_fpm: true
php_fpm_daemon: php-fpm
php_fpm_listen: /var/run/php-fpm/php-fpm.sock
php_fpm_pool_user: '{{ user }}'

php_pecl_extensions:
  - apcu_bc-1.0.3

php_fpm_settings:
  - { setting: listen.owner, value: '{{ user }}' }
  - { setting: listen.group, value: apache }
  - { setting: listen.mode, value: 0660 }

php_settings:
  - { setting: realpath_cache_ttl, value: 7200 }
  - { setting: expose_php, value: 'Off' }

# Apache
apache_global_vhost_settings: |
  DirectoryIndex app.php
  ServerTokens ProductOnly
  ServerSignature Off
  SSLUseStapling on
  SSLStaplingResponderTimeout 5
  SSLStaplingReturnResponderErrors off
  SSLStaplingCache shmcb:/var/run/ocsp(128000)
apache_remove_default_vhost: true
apache_vhosts_filename: '{{ project_name }}.conf'
apache_ssl_protocol: 'All -SSLv3 -TLSv1 -TLSv1.1'
apache_ssl_cipher_suite: 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256'
apache_packages:
  - httpd
  - httpd-devel
  - mod_ssl
  - openssh
apache_vhosts:
  - servername: '{{ host }}'
    extra_parameters: |
      Redirect permanent / https://{{ host }}
apache_vhosts_ssl:
  - servername: '{{ host }}'
    documentroot: '{{ project_remote_folder }}/current/{{ project_relative_index_path }}'
    certificate_file: '/etc/ssl/certs/{{ project_name }}.cert'
    certificate_key_file: '/etc/ssl/private/{{ project_name }}.key'
    extra_parameters: |
      Protocols h2 http/1.1
      ProxyPassMatch ^/(.*\.php)$ "unix:{{ php_fpm_listen }}|fcgi://localhost{{ project_remote_folder }}/current/{{ project_relative_index_path }}"
      Header unset ETag
      FileETag None
      SSLSessionTickets off
