---
php_date_timezone: '{{ timezone }}'
php_error_reporting: 'E_ALL & ~E_DEPRECATED'
php_display_startup_errors: 'Off'
php_opcache_revalidate_path: '1'
php_opcache_enable_cli: '1'
php_opcache_max_accelerated_files: '20000'
php_realpath_cache_size: '5M'
php_enablerepo: ius
php_packages:
  - php71u-devel
  - php71u-cli
  - php71u-fpm-httpd
  - php71u-gd
  - php71u-intl
  - php71u-json
  - php71u-mbstring
  - php71u-mcrypt
  - php71u-mysqlnd
  - php71u-opcache
  - php71u-xml
  - php71u-pecl-apcu
  - php71u-pecl-apcu-devel
php_enable_php_fpm: true
php_fpm_daemon: php-fpm
php_fpm_listen: /var/run/php-fpm/php-fpm.sock
php_fpm_pool_user: '{{ user }}'
php_pecl_extensions:
  - apcu_bc-1.0.3
php_fpm_settings:
  - { setting: listen.owner, value: '{{ user }}' }
  - { setting: listen.group, value: apache }
  - { setting: listen.mode, value: 0660 }
php_settings:
  - { setting: realpath_cache_ttl, value: 7200 }
  - { setting: expose_php, value: 'Off' }
