---
- hosts: all
  become: true
  vars_files:
    - vars/secret.yml
    - vars/configuration.yml
    - vars/project.yml
  gather_facts: false
  pre_tasks:
    - name: Ensure python is installed
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: false
    - setup: # gather_facts
  roles:
    - before
    - Stouts.timezone
    - Stouts.locale
    - GROG.package
    - geerlingguy.certbot
    - ssl
    - geerlingguy.mysql
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.php-pecl
    - geerlingguy.apache-php-fpm
    - after
